
// Full card type to emoji mapping
const emojiMapByType = {
  "Attack": "⚔️",
  "Defense": "🛡️",
  "Loot": "🎒",
  "Tactical": "🧭",
  "Trap": "🧨",
  "Infected": "☣️",
  "Special": "✨",
  "Unique": "🔒"
};

// Full card name to type mapping
const cardTypeLookup = {
  "WinterLand Death Deck (Face-Down)": "Unique",
  "M4-A1": "Attack",
  "AKM": "Attack",
  "Mosin-Nagant": "Attack",
  "SKS": "Attack",
  "CR-527": "Attack",
  "CR-550 Savanna": "Attack",
  "BK-133": "Attack",
  "BK-18": "Attack",
  "MK II": "Attack",
  "FX-45": "Attack",
  "Deagle": "Attack",
  "VSS Vintorez": "Attack",
  "SVD": "Attack",
  "M70 Tundra": "Attack",
  "IZH-18": "Attack",
  "Sawed-off Shotgun": "Attack",
  "USG-45": "Attack",
  "UMP-45": "Attack",
  "KA-74": "Attack",
  "KA-M": "Attack",
  "FAL": "Attack",
  "AK-101": "Attack",
  "AK-74": "Attack",
  "M16-A2": "Attack",
  "SG5-K": "Attack",
  "MP5-K": "Attack",
  "Repeater": "Attack",
  "Derringer": "Attack",
  "Longhorn": "Attack",
  "Crossbow": "Attack",
  "Tactical Vest": "Defense",
  "Ballistic Helmet": "Defense",
  "Assault Helmet": "Defense",
  "Combat Boots": "Defense",
  "Plate Carrier": "Defense",
  "NBC Suit": "Defense",
  "Motorbike Helmet": "Defense",
  "Gorka Jacket": "Defense",
  "Gorka Pants": "Defense",
  "Combat Gloves": "Defense",
  "Hunter Jacket": "Defense",
  "Tactical Shirt": "Defense",
  "Paramedic Jacket": "Defense",
  "Press Vest": "Defense",
  "Firefighter Pants": "Defense",
  "M65 Jacket": "Defense",
  "Riders Jacket": "Defense",
  "Leather Shoes": "Defense",
  "Tracksuit Jacket": "Defense",
  "Military Boots": "Defense",
  "Field Vest": "Defense",
  "Chest Holster": "Defense",
  "Stabproof Vest": "Defense",
  "Assault Backpack": "Defense",
  "Drybag Backpack": "Defense",
  "Tactical Backpack": "Defense",
  "Skate Helmet": "Defense",
  "Boonie Hat": "Defense",
  "Welding Mask": "Defense",
  "Improvised Vest": "Defense",
  "Binoculars": "Tactical",
  "Rangefinder": "Tactical",
  "Handheld Transceiver": "Tactical",
  "Compass": "Tactical",
  "Map": "Tactical",
  "Headtorch": "Tactical",
  "Night Vision Goggles": "Tactical",
  "Tripwire": "Tactical",
  "Duct Tape": "Tactical",
  "Megaphone": "Tactical",
  "Walkie Talkie": "Tactical",
  "Flashlight": "Tactical",
  "Glow Stick": "Tactical",
  "Hunting Scope": "Tactical",
  "Weapon Cleaning Kit": "Tactical",
  "Can of Tactical Bacon": "Loot",
  "MRE": "Loot",
  "Canteen": "Loot",
  "Box of Nails": "Loot",
  "Jerry Can": "Loot",
  "Dynamite": "Loot",
  "First Aid Kit": "Loot",
  "Box of Ammo": "Loot",
  "Fishing Rod": "Loot",
  "Lockpick": "Loot",
  "Battery": "Loot",
  "Rope": "Loot",
  "Cooking Pot": "Loot",
  "Sewing Kit": "Loot",
  "Gun Cleaning Kit": "Loot",
  "Walker (Civilian)": "Infected",
  "Runner (Military)": "Infected",
  "Crawler": "Infected",
  "Burnt Infected": "Infected",
  "Police Infected": "Infected",
  "Hazmat Infected": "Infected",
  "Doctor Infected": "Infected",
  "Hunter Infected": "Infected",
  "Survivor Infected": "Infected",
  "Prisoner Infected": "Infected",
  "Spitter (Mutated)": "Infected",
  "Bloater": "Infected",
  "Fast Infected": "Infected",
  "Butcher Infected": "Infected",
  "Behemoth": "Infected",
  "Bear Trap": "Trap",
  "Tripwire Trap": "Trap",
  "Landmine": "Trap",
  "Makeshift Charge": "Trap",
  "Perimeter Trap": "Trap",
  "Fire Barrel Trap": "Trap",
  "Wire Snare": "Trap",
  "Spiked Log Trap": "Trap",
  "Explosive Grenade Trap": "Trap",
  "Gas Canister Trap": "Trap",
  "Flare Distraction": "Trap",
  "Alarm Tripwire": "Trap",
  "Springloaded Breach Trap": "Trap",
  "IED Pressure Plate": "Trap",
  "Swinging Spiked Bat": "Trap",
  "The Agency": "Special",
  "The Trader": "Special",
  "Jakub Nowak": "Special",
  "Dr. Wesker": "Special",
  "Elena Kovak": "Special",
  "Lt. Col. Emil Bor\u00e9n": "Special",
  "Isabelle Laurent": "Special"
};

document.addEventListener('DOMContentLoaded', () => {
  const cards = document.querySelectorAll('.card-container');
  cards.forEach(card => {
    const nameElements = card.querySelectorAll('p');
    if (nameElements.length > 0) {
      const cardName = nameElements[0].textContent.trim();
      const cardType = cardTypeLookup[cardName];
      if (cardType && emojiMapByType[cardType]) {
        const emojiDiv = document.createElement('div');
        emojiDiv.className = 'card-type-emoji';
        emojiDiv.textContent = emojiMapByType[cardType];
        card.appendChild(emojiDiv);
      }
    }
  });
});
